spring:
  application:
  name: warehouse_management_system
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: azhabko
    password: superuserpassword

server:
  port: 9099
